### ISSUE TITLE
Pretrained models are not available

### ISSUE THREAD

**Issue by sr-jeon** [mu-cai/frequency-domain-image-translation#2]
First of all, thanks for your high-quality codes!

I couldn't find pre-trained models of both swapping autoencoder and starganv2 through the provided links.
I'd appreciate it if you could tell me how to solve it.

**Comment by zq-hznu** [comment]
I have the same problem.Did you solve this problem?

**Comment by mu-cai** [comment]
Hi, thanks for pointing this out. The links are updated now.
