### ISSUE TITLE
training time 

### ISSUE THREAD

**Issue by hughwcq** [mu-cai/frequency-domain-image-translation#6]
hi, great work!
And may ask you about the training time of SwapAE?

**Comment by mu-cai** [comment]
Thank you!
Here are the references for training time for swapping autoencoder.
[https://github.com/taesungp/swapping-autoencoder-pytorch/issues/21](https://github.com/taesungp/swapping-autoencoder-pytorch/issues/21)
[https://github.com/taesungp/swapping-autoencoder-pytorch/issues/2](https://github.com/taesungp/swapping-autoencoder-pytorch/issues/2)
