### ISSUE TITLE
Have you tried official implementation of Swapping Autoencoder?

### ISSUE THREAD

**Issue by xunmeibuyue** [mu-cai/frequency-domain-image-translation#8]
Thanks for this instructive work!
The official Implementation of _Swapping Autoencoder for Deep Image Manipulation_ has already been released at https://github.com/taesungp/swapping-autoencoder-pytorch. I notice that you used an unofficial implementation in your code, so have you tried your method on it?

**Comment by mu-cai** [comment]
We encourage adding our plug-and-play modules into the official implementation, which would be straightforward. The final performance should be similar.
